version: '2'
services:
    jhipsterci-app:
        image: jhipsterci
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterci-postgresql:5432/jhipsterci
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterci-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterci-postgresql
